/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java_crypto_jni_HillJni */

#ifndef _Included_com_java_crypto_jni_HillJni
#define _Included_com_java_crypto_jni_HillJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java_crypto_jni_HillJni
 * Method:    multiplyMatrices
 * Signature: ([[I[[II)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_java_crypto_jni_HillJni_multiplyMatrices
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
